language: java
jdk: oraclejdk8
sudo: false
install: true
cache:
  directories:
  - "$HOME/.m2"
script:
  - mvn clean install
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
    - develop
