pipeline {
    agent any
    tools {
        maven 'Maven 3.3.9'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
                    sh 'mv jenkins/scripts/*.xml ./*.xml'
                    junit 'jenkins/scripts/*.xml'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    sh 'mv jenkins/scripts/*.xml ./*.xml'
                    junit 'jenkins/scripts/*.xml'
                }
            }
        }
    }
}